# 개인 운동 일지로 그래프 만들어보기. 데이터 가공 및 시각화, 분석

## 1) 데이터 가져오기 및 NaN, NaT 데이터 처리.(index는 fillna로 변경 불가 활용)

In [1]:
import pandas as pd
import xlrd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # Windows
# matplotlib.rcParams['font.family'] = 'AppleGothic' # Mac
matplotlib.rcParams['font.size'] = 15
matplotlib.rcParams['axes.unicode_minus'] = False

# df_01 = pd.read_excel('C:/Users/YSJ/Desktop/운동일지/운동일지.xlsx', sheet_name='운동 일지', index_col='날짜', usecols='A:E')
df_02 = pd.read_excel('C:/Users/YSJ/Desktop/운동일지/운동일지.xlsx', sheet_name='2분할 계획표 실시', index_col='날짜', usecols='A:I')

# df_01
df_02.fillna('', inplace=True) # index로 지정된 값들은 fillna로 변경 불가능(아마도 dtype이 다르지 않을까). 먼저 날짜를 제외한 부분의 NaN데이터를 지우고 난 다음, 날짜 부분에서는 ffill로 NaT 데이터를 채운다.
df_02.reset_index(inplace=True)
df_02.fillna(method='ffill', inplace=True)
df_02.set_index('날짜', inplace=True)
df_02

,운동(시간 순서),중량,RIR,1set,2set,3set,4set,5set
날짜,,,,,,,,
2021-03-11,one arm pull up,맨몸,1.5,1,1,1,,
2021-03-11,middle to top position one arm pull up,맨몸-bend,2,3,3,3,,
2021-03-11,middle position negative one arm pull up,맨몸,2,3s,2s,2s,,
2021-03-11,pull up,60kg,1,2,2,,,
2021-03-11,dumbell shrung,40kg,1,5,5,5,,
...,...,...,...,...,...,...,...,...
2022-02-11,dips,맨몸,1,10,10,10,10,10
2022-02-11,dumbell press,25kg,1,6,6,6,,
2022-02-11,bentover lateral raise,12.5kg,1,10,10,10,,
2022-02-11,side lateral raise,5kg,0,20,20,,,
2022-02-11,seated hip thrust,120kg,1,10,10,10,,

## 2) 중량 부분에서 맨몸으로 들어간 부분 83kg으로 변경 및 kg 삭제를 통한 float 값으로 변경